config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  resources :products
  
  root 'page#home'
  
  get 'page/home'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :cart

  def cart  
    session[:cart] ||= {}
  end
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  
  before_action :authenticate_user!
  
  def add
    id = params[:id] 
    cart[id] ? cart[id] = cart[id] + 1 : cart[id] = 1 
    flash[:notice] = "Added to cart"
    redirect_to :back
  end
  
  def clearCart
    session[:cart] = nil
    redirect_to action: :index
  end
  
  def index
    @cart = cart
  end
 
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
  @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :desc, :sku, :price, :brand, :model)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<h1>Your cart</h1>
<% if @cart.empty? %>
  <p></p>
<% else %>
<%= link_to "Empty cart", cart_clear_path %>
<% end %>
<br><br><br>

<% total = 0 %>

<% @cart.each do |id, qty| %>
  <% product = Product.find_by_id(id) %>
  
  <ul>
  <li>
    <%= link_to product.name, product %>
    <p><%= product.desc %></p>
    <p><%= number_to_currency(product.price, unit: '$') %></p>
    <p>Quantity: <%= qty %></p>
  </li>
  </ul>

  <% total += qty*product.price %>
<% end %>

<b>Total: <%= number_to_currency(total, unit: '$') %></b>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <name>RoR Exam for SvitLa</name>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav id="nav">
  <div id="page_nav">
    <%= link_to 'Home', root_path %>
    <%= link_to 'Shop', products_path %>
    <%= link_to "Cart", cart_path %>
  </div>
  
  <div id="sign_in">
    <% if user_signed_in? %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to "Sign In", new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
  </div>
</nav>

<div id="main_wrap">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>


</body>
</html>

app/views/page/home.html.erb
<h1>Welcome to the Ernesto's Exam for Svitla RoR position</h1>
<p>Find me at: <a href="https://www.linkedin.com/in/edelacruzmorales" target="_blank">Linked In</a></p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :sku %><br>
    <%= f.text_field :sku %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products list.</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  Each grid item displays the name of the product, the brand name,
  the model number and the price
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.brand %></td>
        <td><%= product.model %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td>
          <% if user_signed_in? %>
              <%= link_to 'Edit', edit_product_path(product) %>
          <% end %>
        </td>
        <td>
          <% if user_signed_in? %>
              <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
        <td><a href="/cart/<%= product.id %>">Add to Cart</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
    <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.desc %>
</p>

<p>
  <strong>SKU:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @product.model %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<a href="/cart/<%= @product.id %>">Add to Cart</a>